### ISSUE TITLE
코드 수정 사항 

### ISSUE THREAD

**Issue by snoopspy** [Yum-Github/pcap-test#1]
https://github.com/Yum-Github/pcap-test/commit/61db88bc51408dcd8553ac39fa3c183964334184#r38445860

**Comment by Yum-Github** [comment]
done in https://github.com/Yum-Github/pcap-test/blob/master/main.cpp
코드 수정하였습니다~

**Comment by Yum-Github** [comment]
done in https://github.com/Yum-Github/pcap-test/commit/cac9879ac8c57c95bfc1e7d527500e76df11d0e8
코드 수정하였습니다~

**Comment by snoopspy** [comment]
수고하셨습니다.
